"""
初始数据库迁移

Revision ID: 001_initial_migration
Revises: 
Create Date: 2026-02-11 18:46:00.000000
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision = '001_initial_migration'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建data_overview表
    op.create_table('data_overview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('download_time', sa.DateTime(), nullable=True),
    sa.Column('bookname', sa.String(length=500), nullable=True),
    sa.Column('file_extension', sa.String(length=10), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['data_overview.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_data_overview_created_at'), 'data_overview', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_overview_file_name'), 'data_overview', ['file_name'], unique=False)
    op.create_index(op.f('ix_data_overview_file_path'), 'data_overview', ['file_path'], unique=False)
    op.create_index(op.f('ix_data_overview_file_type'), 'data_overview', ['file_type'], unique=False)
    op.create_index(op.f('ix_data_overview_parent_id'), 'data_overview', ['parent_id'], unique=False)
    
    # 创建data_book_detail表
    op.create_table('data_book_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('theories', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('experiment_flow', sa.Text(), nullable=True),
    sa.Column('statistical_methods', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.String(length=20), nullable=True),
    sa.Column('parse_time', sa.DateTime(), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('deepseek_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['data_overview.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_book_detail_created_at'), 'data_book_detail', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_book_detail_file_id'), 'data_book_detail', ['file_id'], unique=True)
    op.create_index(op.f('ix_data_book_detail_parse_status'), 'data_book_detail', ['parse_status'], unique=False)
    
    # 创建data_relationship表
    op.create_table('data_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_overview.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['data_overview.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_relationship_created_at'), 'data_relationship', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_relationship_relation_type'), 'data_relationship', ['relation_type'], unique=False)
    op.create_index(op.f('ix_data_relationship_source_id'), 'data_relationship', ['source_id'], unique=False)
    op.create_index(op.f('ix_data_relationship_target_id'), 'data_relationship', ['target_id'], unique=False)
    
    # 创建user表
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    
    # 创建user_favorite表
    op.create_table('user_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('favorite_type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['data_overview.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorite_created_at'), 'user_favorite', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_favorite_node_id'), 'user_favorite', ['node_id'], unique=False)
    op.create_index(op.f('ix_user_favorite_user_id'), 'user_favorite', ['user_id'], unique=False)
    
    # 创建tag表
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_created_at'), 'tag', ['created_at'], unique=False)
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    
    # 创建file_tag表
    op.create_table('file_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['data_overview.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_tag_created_at'), 'file_tag', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_tag_file_id'), 'file_tag', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_tag_tag_id'), 'file_tag', ['tag_id'], unique=False)
    
    # 创建node_comment表
    op.create_table('node_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(length=20), nullable=True),
    sa.Column('position', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['data_overview.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_comment_created_at'), 'node_comment', ['created_at'], unique=False)
    op.create_index(op.f('ix_node_comment_node_id'), 'node_comment', ['node_id'], unique=False)
    op.create_index(op.f('ix_node_comment_user_id'), 'node_comment', ['user_id'], unique=False)
    
    # 创建parse_log表
    op.create_table('parse_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['data_overview.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parse_log_created_at'), 'parse_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_parse_log_file_id'), 'parse_log', ['file_id'], unique=False)
    op.create_index(op.f('ix_parse_log_task_id'), 'parse_log', ['task_id'], unique=False)
    
    # 创建search_history表
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('search_type', sa.String(length=50), nullable=True),
    sa.Column('filters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_created_at'), 'search_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_history_query'), 'search_history', ['query'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_query'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_created_at'), table_name='search_history')
    op.drop_table('search_history')
    
    op.drop_index(op.f('ix_parse_log_task_id'), table_name='parse_log')
    op.drop_index(op.f('ix_parse_log_file_id'), table_name='parse_log')
    op.drop_index(op.f('ix_parse_log_created_at'), table_name='parse_log')
    op.drop_table('parse_log')
    
    op.drop_index(op.f('ix_node_comment_user_id'), table_name='node_comment')
    op.drop_index(op.f('ix_node_comment_node_id'), table_name='node_comment')
    op.drop_index(op.f('ix_node_comment_created_at'), table_name='node_comment')
    op.drop_table('node_comment')
    
    op.drop_index(op.f('ix_file_tag_tag_id'), table_name='file_tag')
    op.drop_index(op.f('ix_file_tag_file_id'), table_name='file_tag')
    op.drop_index(op.f('ix_file_tag_created_at'), table_name='file_tag')
    op.drop_table('file_tag')
    
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_index(op.f('ix_tag_created_at'), table_name='tag')
    op.drop_table('tag')
    
    op.drop_index(op.f('ix_user_favorite_user_id'), table_name='user_favorite')
    op.drop_index(op.f('ix_user_favorite_node_id'), table_name='user_favorite')
    op.drop_index(op.f('ix_user_favorite_created_at'), table_name='user_favorite')
    op.drop_table('user_favorite')
    
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    
    op.drop_index(op.f('ix_data_relationship_target_id'), table_name='data_relationship')
    op.drop_index(op.f('ix_data_relationship_source_id'), table_name='data_relationship')
    op.drop_index(op.f('ix_data_relationship_relation_type'), table_name='data_relationship')
    op.drop_index(op.f('ix_data_relationship_created_at'), table_name='data_relationship')
    op.drop_table('data_relationship')
    
    op.drop_index(op.f('ix_data_book_detail_parse_status'), table_name='data_book_detail')
    op.drop_index(op.f('ix_data_book_detail_file_id'), table_name='data_book_detail')
    op.drop_index(op.f('ix_data_book_detail_created_at'), table_name='data_book_detail')
    op.drop_table('data_book_detail')
    
    op.drop_index(op.f('ix_data_overview_parent_id'), table_name='data_overview')
    op.drop_index(op.f('ix_data_overview_file_type'), table_name='data_overview')
    op.drop_index(op.f('ix_data_overview_file_path'), table_name='data_overview')
    op.drop_index(op.f('ix_data_overview_file_name'), table_name='data_overview')
    op.drop_index(op.f('ix_data_overview_created_at'), table_name='data_overview')
    op.drop_table('data_overview')
    # ### end Alembic commands ###